### PR TITLE
Add ChatGPT endpoint

### PR DESCRIPTION
**Pull request by alexrudall**
## All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by ScotterC** [comment]
🚀  Super fast! Nice!

**Comment by mkdynamic** [comment]
Thanks @alexrudall!

**Comment by imack** [comment]
`ruby-openai` couldn't have updated *that* fast, I wondered to myself 5 minutes ago.....sure enough

**Comment by DogAndCode** [comment]
Thank you for your amazing job with this gem @alexrudall

**Pull request merged**
