### PR TITLE
Switch to using Typhoeus

### PR DESCRIPTION
**Pull request by alexrudall**
- Typhoeus is faster than HTTParty and allows streaming
- This will be a major breaking change. 
- Maybe we should add an intermediary Response object in addition as suggested [here](https://github.com/alexrudall/ruby-openai/issues/193)?

## Todo

- [ ] Update README examples so they still work

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by cguess** [comment]
I took this branch and added batch queueing as an option as well (using Typhoeus's `Hydra` class). This speeds up getting embeddings of large datasets by multiple orders of magnitude, and handles OpenAI's rate limiting as well.

I'd like to submit this as a sub-PR of this since, especially for researchers, it takes the time to handle 20k+ embeddings from hours to minutes. However, I want to make sure the test coverage is complete and, to be honest, I'm not familiar with VCR and the other testings libraries (always been a minitest guy myself). Is there any chance you (@alexrudall) or someone else could assist with writing the tests after this PR lands?

Thanks for the hard work of porting this library to Typhoeus, I was about to do it myself before I noticed.

**Comment by alexrudall** [comment]
Yeah sure thing! I want to also maybe add an intermediary object as suggested in https://github.com/alexrudall/ruby-openai/issues/193 so there may be a bit of wrangling before it makes it to the gem.

**Comment by cguess** [comment]
Thanks for the quick response @alexrudall. My implementation is block-based so an intermediary object would be more or less zero additional work if there's already an adapter to convert a response object to the new response_object.

I'll keep an eye on #193. Feel free to ping if/when you're ready to take a look.

**Comment by alexrudall** [comment]
If you open a PR I’ll take a look :) thanks!

**Comment by cguess** [comment]
@alexrudall Done, see #196

**Comment by panlilu** [comment]
I can't wait to see this PR merged! Great job on the code, it looks fantastic.

**Comment by timherby** [comment]
@alexrudall I'm using your gem for ChatGPT integration, and running into https://github.com/alexrudall/ruby-openai/issues/164 `Net::ReadTimeout` all the time.  I'd love to take a dependency on this new Typhoeus branch and start playing with it, but it doesn't have the ChatGPT support merged in. 

I'm wondering if I can help you get this over the finish line (though I haven't explored the code for the gem yet), I'd be happy to help out so that we can avoid having to code-up retry logic in our production code.  Please let me know how I can help.

**Comment by frmsaul** [comment]
Thank you. Excited for this change

**Comment by alexrudall** [comment]
> @alexrudall I'm using your gem for ChatGPT integration, and running into #164 `Net::ReadTimeout` all the time. I'd love to take a dependency on this new Typhoeus branch and start playing with it, but it doesn't have the ChatGPT support merged in.
> 
> I'm wondering if I can help you get this over the finish line (though I haven't explored the code for the gem yet), I'd be happy to help out so that we can avoid having to code-up retry logic in our production code. Please let me know how I can help.
> 
> BTW, I'm also very interested in using this for enabling streaming of the responses.

Thanks @timherby ! I'm planning to work on getting this merged next week when I'll have time, really appreciate the offer and may come back to you on that at least for reviews! For now I've merged the [PR](https://github.com/alexrudall/ruby-openai/pull/192) to allow custom HTTParty timeout

**Comment by timherby** [comment]
@alexrudall that's fantastic to hear.  Thank you.  We've got a team working on using the streaming so that we can speed up our responses, so having this branch merged with the ChatGPT support will be what they need.  Happy to take a look at the PR once ready.  

Thanks for the hard work on this library!

**Pull request closed without merging**
