### PR TITLE
Support API Create a thread and run it in one request.

### PR DESCRIPTION
**Pull request by quocphien90**
## Summary
- Support API create a thread and run in one request
Screenshot 2023-11-23 at 22 14 31

## Usage
```ruby
OpenAI::Client.new.runs.create_thread_and_run(
  parameters: {
    assistant_id: assistant_id,
    thread: {
      messages: [{ role: "user", content: "Describe a character called Anna!", file_ids: [] }]
    }
  }
)
```

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Review by cuongn265 — APPROVED** [review]

**Review by beobeboi — APPROVED** [review]

**Review by nguyentran4896 — APPROVED** [review]

**Review by chuducandev — APPROVED** [review]

**Comment by manuelmeurer** [comment]
Would be great to get this merged! :)

**Comment by manuelmeurer** [comment]
@alexrudall Would it be possible to include this in the next release? I've been using it for a month now and it's solid! 🧱

**Comment by manuelmeurer** [comment]
@alexrudall Could we include this PR in the next version please?

**Comment by Saicheg** [comment]
@alexrudall ++ for this endpoint, would be lovely to release it as soon as possible 👁️

**Pull request merged**
