### PR TITLE
Combined Rewrite PR

### PR DESCRIPTION
**Pull request by petergoldstein**
This is a cumulative PR that I'm putting together that includes several changes on top of the initial multi-tenant commit.  In addition to the initial multi-tenant changes it currently includes the following:

1. Updated bundler in the Gemfile.lock to eliminate a runtime deprecation warning
2. Updated rubocop to latest to ensure no lints are introduced
3. Converted of the library to use a consistent top level package of `OpenAI`
4. Refactored the assorted API calls into dedicated classes that are only accessed via the client object
5. Implemented the proposed solution in #142 for the Content-Type / parameters issue
6. Moved the access token check to the `OpenAI::HeadersFactory`
7. Made inclusion of the OpenAI-Organization header contingent on an explicit organization_id
8. Updated specs so that we can test alternate global configurations (the access token is now only pulled from the environment for VCR tests, and the configuration is reset between tests)
9. Refactored the code to extract some embedded logic into dedicated classes to better enable unit testing
10. Updated spec files so that we can run individual spec files, rather than needing to run the entire suite.
11. Consolidated fixture file loading logic into the support file.
12. Added unit tests for OpenAI::Client, OpenAI::JsonlValidator, and OpenAI::HeadersFactory. Also added unit tests for all of the individual endpoint methods.
13. Fixed broken cancel endpoint for finetunes (previously it failed with a null pointer exception)
14. Added checks for required parameters in parameter hashes
15. Removed default parameters arguments from endpoints where they don't make sense (where there is one or more required parameters)
16. Added additional tests for error cases (argument file can't be loaded, etc.)
17. Added a method for the files content endpoint

Both Rubocop and specs pass.  At this point test coverage is ~100%.

Everything appears to be working with the OpenAI API based on my "real" testing.

I do think some additional breaking changes are desirable.  There are two categories of (related) changes I'd suggest:

1. **Use a single exception hierarchy** - Currently a missing file or a file that is not in proper JSONL format expose the underlying error (Errno or JSON::ParseError) respectively.  It would be better if these threw errors that were descendants of OpenAI::Error
2. **Process the return value from HTTParty** - Currently the raw result from HTTParty is passed directly to the client, who is ultimately responsible for figuring out if an error occurred, and for potentially post processing (e.g. parsing JSON into a hash). At a minimum the API should handle errors (translating them into exceptions).  

I'll continue to update with changes.

@alexrudall Any feedback is appreciated.  I also realize this set of changes has gotten quite extensive and opinionated.  If this set of changes doesn't look like something you'd want to incorporate, please let me know.  I'm happy to fork and create an alternate gem.

### CODE REVIEW

**Comment by petergoldstein** [comment]
@alexrudall Just as an FYI, I've taken these changes and a bunch of others and am in the process of creating a new gem (https://github.com/petergoldstein/asimov).

With that in mind I'm not going to spend additional time on this PR - it had grown fairly large and unwieldy.  Please feel free to take anything from it that you find valuable and close it as you see fit.  If you have any questions about these changes, I'm happy to address.

**Comment by unixneo** [comment]
In my view @alexrudall should be focused on substance not form.   Making things "clean and tidy" is certainly a good idea, but since @alexrudall probably does not have unlimited time, he should focus on fixing things which are broken which effect production and expanding new features.   By all means, if @petergoldstein PR's contribute to new features and/or fix production errors, then they should be seriously considered; but on the other hands, if those suggestions which are more cosmetic and stylistic, aka, "code cleanup" should be delayed in favor of the aforementioned comments.

**Comment by alexrudall** [comment]
> In my view @alexrudall should be focused on substance not form. Making things "clean and tidy" is certainly a good idea, but since @alexrudall probably does not have unlimited time, he should focus on fixing things which are broken which effect production and expanding new features. By all means, if @petergoldstein PR's contribute to new features and/or fix production errors, then they should be seriously considered; but on the other hands, if those suggestions which are more cosmetic and stylistic, aka, "code cleanup" should be delayed in favor of the aforementioned comments.

All contributions are gratefully received, I'm just very busy at the moment and always like to test PRs carefully before releasing to limit breakages. Hope to get to these soon!

**Comment by alexrudall** [comment]
Closing this for now as a lot of the changes have made it into the gem now, and this PR is quite diveged. Still some good ideas in here that could be worth adding in future, thanks @petergoldstein

**Pull request closed without merging**
