### PR TITLE
Remove file upload JSON validation

### PR DESCRIPTION
**Pull request by jbeker**
## All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X] Have you added an explanation of what your changes do and why you'd like us to include them?

## Why?

The file upload facility is now used in more places (specifically assistants) that do not have any restrictions on the format of the data that is uploaded. This PR removes the JSON validation on uploading files.

### CODE REVIEW

**Comment by sent-hil** [comment]
@jbeker Why not optionally validate based on parameters? I started working on my own, before seeing this PR. https://github.com/alexrudall/ruby-openai/compare/main...sent-hil:ruby-openai:main

**Comment by jbeker** [comment]
> @jbeker Why not optionally validate based on parameters? I started working on my own, before seeing this PR. https://github.com/alexrudall/ruby-openai/compare/main...sent-hil:ruby-openai:main

In my opinion, validation doesn't have a place here. The API allows uploads of arbitrary files. If someone wants to validate their data, they should do so before trying to upload.

**Comment by johnnagro** [comment]
Ah i didn't see this PR, i just filed a related issue https://github.com/alexrudall/ruby-openai/issues/384

**Comment by jbeker** [comment]
@alexrudall Anything I can do to help move this along? Would love to get off my own branch and using the mainline code :)

**Pull request closed without merging**
