### PR TITLE
Bump event_stream_parser to 1.x.x

### PR DESCRIPTION
**Pull request by atesgoral**
`event_stream_parser` seems to be doing its job. I bumped it to version 1.0.0 to deem the contract stable. No code changes.

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Review by swistaczek — APPROVED** [review]

**Review by codenamev — APPROVED** [review]
Nice 👍

**Comment by atesgoral** [comment]
Or #367 works as well :)

**Comment by chulkilee** [comment]
#367 (`>= 0.3.0, < 2.0.0`) is better than this PR (`>= 1.0.0`) since this PR would disallow 0.3.0 (which actually works) and allow 2.0.0 (which may have breaking changes in the future).

**Comment by alexrudall** [comment]
Thanks all!

**Pull request closed without merging**
