### PR TITLE
Extra headers

### PR DESCRIPTION
**Pull request by deltaguita**
Add extra_headers for cache proxy

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by alexrudall** [comment]
Hey, can you explain what this change is and why it's needed? Thanks :)

**Comment by deltaguita** [comment]
> 

@alexrudall 
For setting [openai cache TTL](https://github.com/6/openai-caching-proxy-worker#specifying-a-cache-ttl)

**Comment by sadfuzzy** [comment]
@alexrudall it is also needed to set Helicone-Auth header

**Review by sadfuzzy — APPROVED** [review]

**Comment by raj-patil53** [comment]
@alexrudall Can we please merge this?

**Comment by deltaguita** [comment]
Hi: @alexrudall 

I've noticed this PR is still open. Could you let me know if there are any changes required for it to be merged?

Thanks

**Comment by marckohlbrugge** [comment]
Would love to get this merged! I actually [made a PR](https://github.com/alexrudall/ruby-openai/pull/295) myself to address this very issue. Didn't realize this PR existed until just now 😅

@deltaguita comparing our diffs, I noticed you're not using the extra headers when using Azure. Something you might want to add.

**Comment by ScotterC** [comment]
I can't remember my exact specifics but when I merged this PR into my branch it was necessary to check if extra_headers were present before merging with other headers like this: https://github.com/ScotterC/ruby-openai/commit/06024ec35e99a133dd60fc8799b551f961e316a9

**Comment by sergeyk** [comment]
Would love for this to be merged as well.

**Comment by alexrudall** [comment]
Thanks for the PRs @deltaguita & @marckohlbrugge and others chasing this! Released in [v4.3](https://rubygems.org/gems/ruby-openai/versions/4.3.0)

**Pull request merged**
