### PR TITLE
Adds the audio Speech API

### PR DESCRIPTION
**Pull request by codergeek121**
I haven't figured out how to filter some headers I'd like to keep hidden (e.g. OpenAI-Org-Id), that's why I haven't committed a working cassette yet. Everything works locally though with a freshly recorded cassette. 

* Adds a simple speech API testcase
* Adds a small documentation section

## All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### CODE REVIEW

**Comment by eltoob** [comment]
Thanks for that!!
Would be great to merge

**Comment by Shpigford** [comment]
Anecdotal feedback for documentation. When I ran this locally, `File.write` gave me an encoding error:

````
irb(main):011> File.write('demo.mp3', response)
(irb):11:in `write': "\xFF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

Opening the file and then writing fixed it for me:

```
File.open('demo.mp3', 'wb') do |file|
  file.write(response)
end
```

**Comment by codergeek121** [comment]
I'll update the docs to use `binwrite` :) Thank you

**Comment by alexrudall** [comment]
Released in [v6.2](https://github.com/alexrudall/ruby-openai/releases), thank you @codergeek121!

**Pull request merged**
